image:
  repository: nullify005/exporter-weather
serviceAccount:
  create: false
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
service:
  enabled: true
  port: 80
  targetPort: 2112
ingress:
  enabled: true
resources:
  limits:
    memory: 128Mi
  requests:
    memory: 128Mi 
livenessProbe:
  path: /health
  port: 2112
readinessProbe:
  path: /health
  port: 2112
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "2112"
command:
- /exporter-weather
