{
 "title": "Observations",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(observation_humidity)/count(observation_humidity)",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "sum(observation_rain_since_9am_mm)/count(observation_rain_since_9am_mm)",
     "legendFormat": "mm rain since 9am"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(observation_temperature_celcius)/count(observation_temperature_celcius)",
     "legendFormat": "Temperature"
    },
    {
     "expr": "sum(observation_temperature_feelslike_celcius)/count(observation_temperature_feelslike_celcius)",
     "legendFormat": "Feels Like"
    }
   ]
  },
  {
   "title": "Windspeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "sum(observation_windspeed_kph)/count(observation_windspeed_kph)",
     "legendFormat": "Windspeed"
    },
    {
     "expr": "sum(observation_windspeed_gust_kph)/count(observation_windspeed_gust_kph)",
     "legendFormat": "Gusts"
    }
   ]
  }
 ]
}