helmDefaults:
  wait: true
  atomic: true
  verify: false # necessary as this is a local chart
  timeout: 30

environments:
  local: {}
  development: {}

releases:
- name: app
  namespace: exporter-weather-{{ .Environment.Name }}-v1
  createNamespace: true
  chart: ../helm/charts/exporter-weather
  values:
  - ../helm/values/app/common.yaml
  - ../helm/values/app/{{ .Environment.Name }}.yaml\
  {{ if eq .Environment.Name "development" }}
  - ../secrets/version.yaml
  {{ end }}

